### PR TITLE
More documentation and better decoding of Fujitsu packets

### PR DESCRIPTION
**Pull request by andrewerrington**
I have a Fujitsu heat pump (in New Zealand), with remote control model AR-RAH1E. Documentation of this protocol is sparse, but I have pulled as much as I can together from around the web into the comments of the Fujitsu.cpp file. A lot of the concrete information came from a work done by David Abrams in a PDF file here: http://files.remotecentral.com/view/6811-18313-1/fujitsu_minisplit_air_conditioner.html

I have checked the codes that are supported by my remote and taken the PDF information and rewritten it as text for easy accessibility. I have also read several manuals for different variants of this remote to glean more details of other likely commands, and added those that can be generated by my remote. 

I have re-written the code to pull apart the IR packet and display the meaning of each field within the packet. I hope that others will try it out and document any differences they see. Next, I want to make an ESP8266-based remote control using the other code from @ToniA. I will check the packet construction code and I will use this decoding software to verify that the synthesised packets match those generated by the real remote.

### CODE REVIEW

**Comment by ToniA** [comment]
Thank you Andrew, this is a really good contribution :)

**Comment by givanildo** [comment]
Toni , first of all   Thanks for your work!!
I need decode ac protocols using a esp8266.  Work ok with arduino.  But in esp I have a trouble because IRPin_pin (PINE or PIND ) not working in manipulation port in the Esp.
Sorry about my bad English 
May you help me?

**Comment by givanildo** [comment]
The reason for this is that I intend to use a wemos oled to show the temperature selected by the remote control and also the humidity and temperature using a dth11

**Comment by givanildo** [comment]
My air conditioner does not have a display.

**Pull request merged**
